[package]
name = "near-store"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2"
derive_more = "0.99.3"
elastic-array = "0.11"
lazy_static = "1.4"
rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb", rev = "d6c779c179aa3e5f68e4d6a3dfef27a6f776d92c" }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
cached = "0.12"
num_cpus = "1.11"
rand = "0.7.2"
strum = "0.18"
strum_macros = "0.18"

borsh = "0.7.0"

near-crypto = { path = "../crypto" }
near-primitives = { path = "../primitives" }

[dev-dependencies]
tempfile = "3"
bencher = "0.1.5"
rand = "0.7"

[[bench]]
name = "trie_bench"
harness = false

[features]
default = []
no_cache = []
adversarial = []
